pref("extensions.importexporttools.export.filenames_toascii", false);
pref("extensions.importexporttools.export.overwrite", false);
pref("extensions.importexporttools.confirm.before_mbox_import", true);
pref("extensions.importexporttools.clipboard.always_just_text", false);
pref("extensions.importexporttools.export.HTML_as_displayed", false);
pref("extensions.importexporttools.exportEML.filename_format", 0);
pref("extensions.importexporttools.delay.clean_statusbar", 5000);
pref("extensions.importexporttools.subject.max_length", 50);
pref("extensions.importexporttools.author.max_length", 50);
pref("extensions.importexporttools.recipients.max_length", 50);
pref("extensions.{3ed8cc52-86fc-4613-9026-c1ef969da4c3}.description", "chrome://mboximport/locale/extensions.importexporttools.properties");
pref("extensions.importexporttools.export.set_filetime", false);
pref("extensions.importexporttools.exportEML.use_dir", false);
pref("extensions.importexporttools.exportMBOX.use_dir", false);
pref("extensions.importexporttools.exportMSG.use_dir", false);
pref("extensions.importexporttools.export.filenames_addtime", false);
pref("extensions.importexporttools.export_all.warning1", true);
pref("extensions.importexporttools.export_all.warning2", true);
pref("extensions.importexporttools.import.build_mbox_index" , true);
pref("extensions.importexporttools.export.format_warning", true);
pref("extensions.importexporttools.export.cut_subject", false);
pref("extensions.importexporttools.export.cut_filename", true);
pref("extensions.importexporttools.export.filename_add_prefix", false);
pref("extensions.importexporttools.export.filename_charset", "");
pref("extensions.importexporttools.export.use_container_folder", true);
pref("extensions.importexporttools.sms.add_subject", true);
pref("extensions.importexporttools.autobackup.last", 0);
pref("extensions.importexporttools.autobackup.type", 0);
pref("extensions.importexporttools.autobackup.frequency", 0);
pref("extensions.importexporttools.autobackup.dir_name_type", 0);
pref("extensions.importexporttools.autobackup.save_mode", 2);
pref("extensions.importexporttools.export.remote_warning", true);
pref("extensions.importexporttools.export.skip_existing_msg", false);
pref("extensions.importexporttools.autobackup.use_modal_dialog", true);
pref("extensions.importexporttools.import.name_add_number", false);
pref("extensions.importexporttools.export.use_converter", false);
pref("extensions.importexporttools.export.text_plain_charset", "UTF-8");
pref("extensions.importexporttools.log.enable", false);
pref("extensions.importexporttools.csv_separator", ",");
pref("extensions.importexporttools.migrate_prefs", true);
pref("extensions.importexporttools.export.import_warning", true);
pref("extensions.importexporttools.export.mail_separator", "-------------------------");
pref("extensions.importexporttools.printPDF.fileFormat", 2);
pref("extensions.importexporttools.reset_mozilla_status", false);
pref("extensions.importexporttools.export.charset_list", "ARMSCII-8,GEOSTD8,ISO-8859-1,ISO-8859-2,ISO-8859-3,ISO-8859-4,ISO-8859-5,ISO-8859-6,ISO-8859-7,ISO-8859-8,ISO-8859-9,ISO-8859-10,ISO-8859-11,ISO-8859-12,ISO-8859-13,ISO-8859-14,ISO-8859-15,ISO-8859-16,KOI8-R,KOI8-U,UTF-8,UTF-8 (BOM),WINDOWS-1250,WINDOWS-1251,WINDOWS-1252,WINDOWS-1253,WINDOWS-1254,WINDOWS-1255,WINDOWS-1256,WINDOWS-1257,WINDOWS-1258");


